### ISSUE TITLE
ReadFile returns "not ended with .txt"

### ISSUE THREAD

**Issue by JohnWins** [Ahmadmansoor/AdvancedScript#8]
hi,_  there

Simple script here:

> varx int,vA,0 
varx str,vE,"C:\\abc.txt"
varx array,vB[1],0
movx $A,1234
ReadFile $vE,$vB[0]
ReadFile "C:\\abc.txt",$vB

it always returns 
>not ended with .txt
this Line have error 
ReadFile $vE,$vB[0]

any suggestion?

**Comment by Ahmadmansoor** [comment]
HI
and thanks for trying the plugin,the code should be like this :

> varx int,vA,0
varx str,vE,"D:\abc.txt"
varx array,vB[1],0
$vA=1234
ReadFile $vB,$vE

movx is used to get value from AdvancedScript system to x64dbg system pls check the read me 
sample :

> movx eax,$vA

in other hand if u want to assigned a value to variable all u have to do it just use = operator 
like this :

> $vA=1234

or u can use Setx Function 
why there are 2 way to assigned because if u want to use conditional PB u have to use Setx Function 
to make the command recognized  in conditional PB , as the  AdvancedScript system who analyzed 
the  = operator ,so it will know that is same.
AdvancedScript system:

> $vA=1234

or 

> Setx $vA,1234

conditional PB:

> Setx $vA,1234

/////
for the ReadFile  Function u should not add [] to name of variable, just make sure that the variable is array that's all  :)
like this :

> ReadFile $vB,$vE

**Comment by JohnWins** [comment]
wow, the ReadFile function works ! 
>vE is path, and vB is an array variable, as what you write above.

but it's different from the helpAdvancedScript.txt.

> ReadFile path,Array Variable
 - in parameter 1 :set the path of the file it can be done by variable other wise use "" surrounded path.
 - in parameter 2 :array variable

Maybe something goes wrong.

**Comment by Ahmadmansoor** [comment]
Lol you are right ,I have to update the ReadMe and the Help manual :)
sorry for this

**Comment by JohnWins** [comment]
It's a very nice script system, keep trying :)
and it might be easier to translate more command on OllyDbg for begainers .:)
